### ISSUE TITLE
Exception Handling for EGL api calls

### ISSUE THREAD

**Issue by bensinghbeno** [Luxoft/Safe-Renderer#4]
As a general development guideline/approach it's really safer to handle exceptions when we call/use api's from 3rd parties. Since LSR already has "pilassert" lib, can we implement exception handling for all 3rd party calls?.

For example in gil.c, the "eglGetConfigAttrib()" egl code could be enclosed inside an exception handler to handle egl exceptions.

static NativeWindowType getNativeWindow(NativeDisplayType dsp, int32_t width, int32_t height)
{
    eglGetConfigAttrib(m_display.egl, m_config, EGL_NATIVE_VISUAL_ID, &format);

**Comment by ArwedL** [comment]
Hi Beno,

I see you are Luxoft employee. You can also contact me directly (Arwed Richert) so we can discuss details.

BR,

Arwed
